---
tasks:
  - name: "Instalar dependencias de Composer"
    command: "composer install --no-dev --optimize-autoloader"

  - name: "Generar clave de la aplicación"
    command: "php artisan key:generate"

  - name: "Migrar la base de datos"
    command: "php artisan migrate --force"

  - name: "Ejecutar seeders"
    # command: "php artisan db:seed --force"
    commad:"  php artisan db:seed
              php artisan db:seed UsersSeeder
              php artisan db:seed TestSeeder
              php artisan db:seed DoctorSeeder
              php artisan db:seed InsuranceSeeder"

  - name: "Compilar estilos CSS"
    command: "npm run prod"
